"""Initial schema

Revision ID: 9962d8d4e657
Revises: 2d502d25e0ab
Create Date: 2026-07-21 06:20:07.387354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9962d8d4e657'
down_revision: Union[str, None] = '2d502d25e0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_inventory_id'), 'inventory_movements', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_po_items_po_id'), 'po_items', ['po_id'], unique=False)
    op.create_index(op.f('ix_po_items_product_id'), 'po_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_destination_warehouse_id'), 'purchase_orders', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_recommendations_product_id'), 'recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_recommendations_warehouse_id'), 'recommendations', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_product_id'), 'reconciliation_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_reconciliation_id'), 'reconciliation_items', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_reconciliations_warehouse_id'), 'reconciliations', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_source_warehouse_id'), 'sales', ['source_warehouse_id'], unique=False)
    op.create_index(op.f('ix_transfer_items_product_id'), 'transfer_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_transfer_items_transfer_id'), 'transfer_items', ['transfer_id'], unique=False)
    op.create_index(op.f('ix_transfers_destination_warehouse_id'), 'transfers', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_transfers_source_warehouse_id'), 'transfers', ['source_warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_source_warehouse_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_destination_warehouse_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfer_items_transfer_id'), table_name='transfer_items')
    op.drop_index(op.f('ix_transfer_items_product_id'), table_name='transfer_items')
    op.drop_index(op.f('ix_sales_source_warehouse_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_reconciliations_warehouse_id'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliation_items_reconciliation_id'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_product_id'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_recommendations_warehouse_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_product_id'), table_name='recommendations')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_destination_warehouse_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_po_items_product_id'), table_name='po_items')
    op.drop_index(op.f('ix_po_items_po_id'), table_name='po_items')
    op.drop_index(op.f('ix_inventory_movements_inventory_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    # ### end Alembic commands ###
